config/routes.rb
OnePercent::Application.routes.draw do
  resources :quotes

  root :to => 'stocks#today'
  get  'about' => "stocks#about"

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :date, :eps_actual, :eps_estimate, :neg1_close, :neg1_open, :stock_id, :timing, :zero_close, :zero_open
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def today
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">One Percent</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav nav-tabs">
      		<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>

      <div class="nav-collapse collapse pull-right">
      	<ul class="nav nav-tabs">
      		<li><%= link_to "Signin", "#" %></li>
			
		</ul>

        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnePercent</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>	
	<%= render 'layouts/header' %>

	<div class="container">	
		<%= yield %>
	</div>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock_id %><br />
    <%= f.number_field :stock_id %>
  </div>
  <div class="field">
    <%= f.label :neg1_open %><br />
    <%= f.text_field :neg1_open %>
  </div>
  <div class="field">
    <%= f.label :neg1_close %><br />
    <%= f.text_field :neg1_close %>
  </div>
  <div class="field">
    <%= f.label :zero_open %><br />
    <%= f.text_field :zero_open %>
  </div>
  <div class="field">
    <%= f.label :zero_close %><br />
    <%= f.text_field :zero_close %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :timing %><br />
    <%= f.text_field :timing %>
  </div>
  <div class="field">
    <%= f.label :eps_estimate %><br />
    <%= f.text_field :eps_estimate %>
  </div>
  <div class="field">
    <%= f.label :eps_actual %><br />
    <%= f.text_field :eps_actual %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <tr>
    <th>Stock</th>
    <th>Neg1 open</th>
    <th>Neg1 close</th>
    <th>Zero open</th>
    <th>Zero close</th>
    <th>Date</th>
    <th>Timing</th>
    <th>Eps estimate</th>
    <th>Eps actual</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.stock_id %></td>
    <td><%= quote.neg1_open %></td>
    <td><%= quote.neg1_close %></td>
    <td><%= quote.zero_open %></td>
    <td><%= quote.zero_close %></td>
    <td><%= quote.date %></td>
    <td><%= quote.timing %></td>
    <td><%= quote.eps_estimate %></td>
    <td><%= quote.eps_actual %></td>
    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @quote.stock_id %>
</p>

<p>
  <b>Neg1 open:</b>
  <%= @quote.neg1_open %>
</p>

<p>
  <b>Neg1 close:</b>
  <%= @quote.neg1_close %>
</p>

<p>
  <b>Zero open:</b>
  <%= @quote.zero_open %>
</p>

<p>
  <b>Zero close:</b>
  <%= @quote.zero_close %>
</p>

<p>
  <b>Date:</b>
  <%= @quote.date %>
</p>

<p>
  <b>Timing:</b>
  <%= @quote.timing %>
</p>

<p>
  <b>Eps estimate:</b>
  <%= @quote.eps_estimate %>
</p>

<p>
  <b>Eps actual:</b>
  <%= @quote.eps_actual %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/stocks/about.html.erb
<h1>About this site</h1>

app/views/stocks/today.html.erb
<div class="hero-unit">
	<h1>Today is the greatest day I've ever known</h1>
	<p>Can't live for tomorrow</p>
</div>